### ISSUE TITLE
How the reward function working

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRL#11]
Hello:
        Here is a question when I used the deep reinforcement learning.I got the reward,and I wonder how does this reward guide the PPO to train the ANNs?In other words,how can I  connect the reward and the PPO,and which part of this program show this proess!
       Thank you

**Comment by jerabaul29** [comment]
Hi!

I recommend that you read in details:

- https://arxiv.org/pdf/1906.10382.pdf (in its newest version from 12.08.2019, you may need to do a refresh if you had visited this page before)

- https://arxiv.org/pdf/1908.04127.pdf

Those two preprints should make things clear.

The problem is that the CFD is very slow compared with the DRL. So this repo:

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

will release the code of the first preprint once it gets published.

If you are interested in using the parallel code before our article gets published, you should send me an email at jeanra@math.uio.no and we can discuss to collaborate, in which case I can share my code in advance with you.

**Comment by yangtianyong** [comment]
well thank you for you answering!

**Comment by yangtianyong** [comment]
Hello:
         First ,thanks for offering me the materials a few days ago.Now I want to make sure my thought is right after I  read those materials.
         That is ,at the begin,I get a reward,in order to maximum the reward ,and I can change weights based on the  PPO Gradient formula;then everytime I get a new reward,add those reward up,again maximum the reward,change weights ...At last ,find a biggest one.
          Am I right?thank you!

**Comment by jerabaul29** [comment]
Hi!

This is a way to put it up.

Cheers,

Jean
