### ISSUE TITLE
About Q<0.06

### ISSUE THREAD

**Issue by yangtianyong** [jerabaul29/Cylinder2DFlowControlDRL#22]
hello:
      I found that you set up |Q|<0.06，to prevent non-physically large actuation.And I  can not find where the programm to achieve this function.
    It would be nice if you can tell me where I can find The Q in programm

**Comment by jerabaul29** [comment]
Hi,

You may have to dig a bit in the code to find where this impacts the code further, but this is basically set here if I remember well:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/44f526f45187eb63e06bea9c586e9efa6a04650d/Cylinder2DFlowControlWithRL/ANN_controlled_flow_learning/env.py#L101-L102

And the main position where this parameter is used is here:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL/blob/44f526f45187eb63e06bea9c586e9efa6a04650d/Cylinder2DFlowControlWithRL/Env2DCylinder.py#L889-L903

(note that on newer TensorForce versions, the API may be slightly different).

The value is not exactly the same as in the paper, due to the different conventions used between the paper (non dimensional) and the code ("native" units, see the discussions in the "Confusing choices in the code" section of the Readme).

That should put you on the right track, closing, if anything is unclear feel free to re-open.
