### ISSUE TITLE
Negative drag values while training

### ISSUE THREAD

**Issue by troy1729** [jerabaul29/Cylinder2DFlowControlDRL#24]
Hi,

I've recently started using RL to fluid problems. So please excuse for naive questions. While training, the value of drag force is coming negative using fenics. Then how come Cd graph is plotted with the positive value? Can you elaborate

**Comment by jerabaul29** [comment]
I have not used this code for a long time, but if I remember well, this is just a question of sign - i.e. is the force / "drag" coefficient computed from the point of view of the cylinder or the point of view of the fluid, and which conventions are chosen. To make things even more confusing, we are interested in reducing the drag, while the DRL algorithm tries to maximize the reward; so, in the end, you always end up with a different "sign" needed between the Cd and the reward.

**Comment by troy1729** [comment]
Thanks that is good direction for me to look into regarding negative sign. Also the plot in the paper shows reduction of cd from ~3.4 to ~3 for Re 100. But while training, even the drag magnitude is in the 0.1 scale. So is it the drag force that is getting printed while training or I'm missing something? 

For instance "Rec Area: 0.0113, drag: -0.1635, lift: 0.0957"

**Comment by jerabaul29** [comment]
The information printed in terminal is raw "force", "non scaled" data, while the paper presents "scaled" drag coefficient etc. I.e. this is because the terminal spits out drag, while the paper reports the scaled drag coefficient. See the section "[](https://github.com/jerabaul29/Cylinder2DFlowControlDRL#confusing-choices-in-the-code)Confusing choices in the code" of the README file, and the links to the discussions https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/3 and https://github.com/jerabaul29/Cylinder2DFlowControlDRL/issues/6 therein.

**Comment by jerabaul29** [comment]
Closing for now, as the answer is "read the readme for more details" :) . You may also want to look at the code in details to understand exactly what is being done.
