### ISSUE TITLE
issues about running single_runner.py

### ISSUE THREAD

**Issue by zhaoyr31** [jerabaul29/Cylinder2DFlowControlDRL#25]
Mr. Jean, after I downloaded singularity and your container, I tried to run single_runner.py in singularity. However, it seemed something went wrong. Was it about not downloading tensorforce, python and so on successfully? Hope to get your instruction.

**Singularity> exec '/home/yr/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/baseline_flow/single_runner.py' 
from: can't read /var/mail/printind.printind_function
from: can't read /var/mail/env
/home/yr/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/baseline_flow/single_runner.py: line 4: import: command not found
from: can't read /var/mail/tensorforce.agents
from: can't read /var/mail/tensorforce.execution
/home/yr/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/baseline_flow/single_runner.py: line 7: import: command not found
/home/yr/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/baseline_flow/single_runner.py: line 8: import: command not found
/home/yr/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/baseline_flow/single_runner.py: line 9: import: command not found
/home/yr/Cylinder2DFlowControlDRL-master/Cylinder2DFlowControlWithRL/baseline_flow/single_runner.py: line 18: 
import sys
import os
cwd = os.getcwd()
sys.path.append(cwd + /../Simulation/)**

**Comment by jerabaul29** [comment]
- I am not really sure if you actually are running from inside the singularity container; can you show the full terminal output you get also with the previous commands you run, ie start showing your terminal at issuing the command to start the singularity container? (can you show the previous commands you wrote and the corresponding output?)

- once you are in singularity, you should just run your python script "as usual", there is no more "exec" command; the exec command was to start the singularity container. So you should just ```cd``` to the right folder, and there issue the ```python3 single_runner.py``` command.

There is a video of how to do this in docker with the parallelized code from https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel in the repository of one paper: see the video on https://github.com/thw1021/Cylinder2DFlowControlGeneral , i.e. https://asciinema.org/a/326357 . That illustrates the full process (though this uses the more modern parallel code using docker rather than the older code using singularity).

Please look at the full video there, make sure you understand all of it, and then either apply the same methodology as presented in the video and explained in the readme here to use the singularity code, or if you prefer, use the more modern docker code exactly as shown in the video.

**Comment by zhaoyr31** [comment]
Thanks!
My input was the same as you have mentioned: **singularity shell /home/yr/fenics-and-more.img -c "export DISPLAY=:0.0 && export PATH="/home/yr/gmsh-git-Linux64/bin:$PATH" && /bin/bash"**, after I wrote it in my terminal, it showed "**Singularity>**" on the screen, so I guess I had entered the singularity container?
Well, it seems there are still lots of things which I should know. I will learn videos you offered as soon as possible. Thanks again for your patient reply!

**Comment by jerabaul29** [comment]
Ok, so then it means that you are well inside the container :) .

If I remember well, the code is already in the container. You will have to go to the right folder. Can you show me the content of the current folder as provided by ```ls```?

**Comment by zhaoyr31** [comment]
The folder contained things below.

**Cylinder2DFlowControlDRL-master      fenics-and-more.img_part.ae  ??????
Cylinder2DFlowControlDRL-master.zip  fenics-and-more.img_part.af  ??????
build				     gmsh-3.0.6-Linux64		  ??????
fenics-and-more.img		     go				  ??????
fenics-and-more.img_part.aa	     singularity-ce-3.9.5	  ??????
fenics-and-more.img_part.ab	     snap			  ??????
fenics-and-more.img_part.ac	     ??????
fenics-and-more.img_part.ad	     ?????????**

Does it mean everything go well?

**Comment by jerabaul29** [comment]
Can you show the full command you issue with the prompt? This is I think not the singularity folder but the host folder.

**Comment by jerabaul29** [comment]
See in the Readme the sections "Launching one episode without training" and following.

**Comment by jerabaul29** [comment]
I am 100% sure this works, it has been used by many people over the years. It does assume you are familiar with Unix and command line and containerization. If you are not familiar with these, you should read some courses / tutorials online :) .

**Comment by zhaoyr31** [comment]
I realized the same later (it was the host folder). It's true that I'm a new learner in the field, so I should learn more at first. Thanks for your time : ).

**Comment by jerabaul29** [comment]
😊👍

**Comment by jerabaul29** [comment]
I understand this is working now, closing, if you have more issues feel free to open new issues.
