### ISSUE TITLE
Controlled action

### ISSUE THREAD

**Issue by HazemKhaledAbdallah** [jerabaul29/Cylinder2DFlowControlDRL#31]
Hello Sir,

Thank you for sharing such impressive work. I’ve noticed that many papers have developed Python libraries based on your method, and I truly appreciate the contributions to the field. I have a question regarding the controlled equation for the jet. Most of the papers I’ve encountered utilize the following form:

cs+1 = cs + α(a − cs)

I’m curious why this form is preferred. Why isn't  based on frequency and amplitude, such as u-j = U * A * sin(2π * F * t), used more commonly? Would using this form  pose significant challenges in terms of training or stability?

Thanks in advance for your insights.

**Comment by jerabaul29** [comment]
Hi,

I think you refer to the interpolation from the previous to the next action.

For this, the requirement is to go "smoothly" from one action applied to the CFD to the next action (a) provided by the agent. This can be done either through an exponential decay (as was done in https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/abs/artificial-neural-networks-trained-through-deep-reinforcement-learning-discover-control-strategies-for-active-flow-control/D5B80D809DFFD73760989A07F5E11039 since this was the simplest to implement, see discussion around "The control is made continuous in time to avoid jumps..."), or a linear interpolation (as was done in https://pubs.aip.org/aip/pof/article-abstract/32/5/053605/1033993/Robust-active-flow-control-over-a-range-of?redirectedFrom=fulltext ; this is a bit more work, but gives smoother control, see fig. 8 and related discussion, see "After extensive trial-and-error, it is finally found that linear..."), or a C-inf interpolation: see the discussion around "Smooth transition functions" in https://en.wikipedia.org/wiki/Non-analytic_smooth_function. This is what is used in more recent works such as e.g. https://arxiv.org/abs/2309.02462 .

In the end, usually a smoother transition is better, but it is just more work to implement - so in this first work, we had started with a simple "exponential decay to the next control value".

**Comment by HazemKhaledAbdallah** [comment]
Thanks a lot for your detailed response . Yes, this is what I am asking about implementing a sine wave velocity profile so you can apply ZNMF for each jet as mentioned here (recent works such as e.g. https://arxiv.org/abs/2309.02462 ). However, it seems more challenging as they use Multi-Agent , and I don't know if there is a similar code  accessible like your work. Also, If you know a library which do like your code and interact with openFoam but can be implemented on HPC including the steps of submitting the job , please share with me .
Regards

**Comment by jerabaul29** [comment]
I think there are 2 different things:

- the profile of the velocity, in space, around the injection location (in this study, a cosine profile in space with opposite coefficient at the top and bottom of the cylinder to enforce ZNMF)
- the way you transition in time from one action to the next one, i.e. how you smooth the time transition from one action to the next one; this is where the C-inf transition comes in.

I am not sure which one you refer to, but as long as these points are clear in your head, you should be good to go :) .

**Comment by HazemKhaledAbdallah** [comment]
Ok thanks for clarification, i was thinking the sin profile will oscillate between injection and suction for just 1 jet  through each interaction period and as a result, ZNMF will be achieved with out considering another jet with opposite coefficient (is it possible or it will be challenging for transition with time).

**Comment by jerabaul29** [comment]
I don't think this will work, because then the agent cannot consistently remove fluid where it needs and add some where it needs. But never know.

**Comment by HazemKhaledAbdallah** [comment]
OK thanks a lot for your time and guidance.
Regards
